server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: task-service
          uri: http://task-service:8050
          predicates:
            - Path=/tasks/**
          filters:
            - StripPrefix=0
        - id: users
          uri: http://auth-service:8090
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: project-service
          uri: http://project-service:8070
          predicates:
            - Path=/projects/**
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
