server:
  port: 8090

spring:
  application:
    name: users
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    compatibility-verifier:
      enabled: false

token:
  signing:
    key: ${JWT_SECRET_KEY}
    lifetime: 3600000